Playbook for limit local account use of blank password:
---
- name: Configure security settings for Windows
  hosts: windows_servers
  gather_facts: yes
  become: yes

  tasks:
    - name: Limit local account use of blank passwords to console logon only
      win_security_policy:
        name: LimitBlankPasswordUse
        state: present
        value: 1

    - name: Digitally encrypt or sign secure channel data (always)
      win_security_policy:
        name: SeAlwaysEncryptSecureChannel
        state: present
        value: 1

    - name: Digitally encrypt secure channel data (when possible)
      win_security_policy:
        name: SeEncryptSecureChannel
        state: present
        value: 1

    - name: Digitally sign secure channel data (when possible)
      win_security_policy:
        name: SeSignSecureChannel
        state: present
        value: 1

    - name: Disable machine account password changes
      win_security_policy:
        name: RefusePasswordChange
        state: present
        value: 1

    - name: Maximum machine account password age
      win_security_policy:
        name: MaximumPasswordAge
        state: present
        value: 30

    - name: Require strong (Windows 2000 or later) session key
      win_security_policy:
        name: RequireStrongKey
        state: present
        value: 1

- name: Configure security settings for Linux
  hosts: linux_servers
  gather_facts: yes
  become: yes

  tasks:
    - name: Require strong (Windows 2000 or later) session key
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^KexAlgorithms'
        line: 'KexAlgorithms'

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted